### Step 1: Loading the data

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv('../data/Churn_Modelling.csv')

### Step 2: Visualizing the data

In [3]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [5]:
data.corr()

RowNumber  CustomerId  CreditScore       Age    Tenure  \
RowNumber         1.000000    0.004202     0.005840  0.000783 -0.006495   
CustomerId        0.004202    1.000000     0.005308  0.009497 -0.014883   
CreditScore       0.005840    0.005308     1.000000 -0.003965  0.000842   
Age               0.000783    0.009497    -0.003965  1.000000 -0.009997   
Tenure           -0.006495   -0.014883     0.000842 -0.009997  1.000000   
Balance          -0.009067   -0.012419     0.006268  0.028308 -0.012254   
NumOfProducts     0.007246    0.016972     0.012238 -0.030680  0.013444   
HasCrCard         0.000599   -0.014025    -0.005458 -0.011721  0.022583   
IsActiveMember    0.012044    0.001665     0.025651  0.085472 -0.028362   
EstimatedSalary  -0.005988    0.015271    -0.001384 -0.007201  0.007784   
Exited           -0.016571   -0.006248    -0.027094  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber       -0.009067       0.007246   0.000599        0.012044   
CustomerId      -0.012419       0.016972  -0.014025        0.001665   
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
RowNumber              -0.005988 -0.016571  
CustomerId              0.015271 -0.006248  
CreditScore            -0.001384 -0.027094  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

In [6]:
# Labels? (Total number of positive cases)
data['Exited'].sum()

2037

In [7]:
# Number and names of categorical entries
print("Surname:")
print(data['Surname'].nunique())
print(data['Surname'].unique())
print()
print("Geography:")
print(data['Geography'].nunique())
print(data['Geography'].unique())
print()
print("Gender:")
print(data['Gender'].nunique())
print(data['Gender'].unique())

Surname:
2932
['Hargrave' 'Hill' 'Onio' ... 'Kashiwagi' 'Aldridge' 'Burbidge']

Geography:
3
['France' 'Spain' 'Germany']

Gender:
2
['Female' 'Male']


## Running model

In [1]:
from pytorch.customer_churn_prediction import main
from argparse import Namespace

args = Namespace(batch_size=14, epochs=100, lr=0.01, input_dim=13, output_dim=2, data_dir='../data/Churn_Modelling.csv', test_size=0.2)
main(args)

Train Epoch: 0 [0/8000 (0%)]	Loss: 0.584051
Train Epoch: 0 [1400/8000 (17%)]	Loss: 0.348156
Train Epoch: 0 [2800/8000 (35%)]	Loss: 0.363388
Train Epoch: 0 [4200/8000 (52%)]	Loss: 0.485302
Train Epoch: 0 [5600/8000 (70%)]	Loss: 0.446140
Train Epoch: 0 [7000/8000 (87%)]	Loss: 0.520859

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 1 [0/8000 (0%)]	Loss: 0.387808
Train Epoch: 1 [1400/8000 (17%)]	Loss: 0.322274
Train Epoch: 1 [2800/8000 (35%)]	Loss: 0.364290
Train Epoch: 1 [4200/8000 (52%)]	Loss: 0.486450
Train Epoch: 1 [5600/8000 (70%)]	Loss: 0.447236
Train Epoch: 1 [7000/8000 (87%)]	Loss: 0.521105

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 2 [0/8000 (0%)]	Loss: 0.387712
Train Epoch: 2 [1400/8000 (17%)]	Loss: 0.322828
Train Epoch: 2 [2800/8000 (35%)]	Loss: 0.364308
Train Epoch: 2 [4200/8000 (52%)]	Loss: 0.486650
Train Epoch: 2 [5600/8000 (70%)]	Loss: 0.447443
Train Epoch: 2 [7000/8000 (87%)]	Loss: 0.521223

Test set: Average loss: 0.0

Train Epoch: 24 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 24 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 24 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 24 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 24 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 25 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 25 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 25 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 25 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 25 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 25 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 26 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 26 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 26 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 26 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 26 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 26 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (7


Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 48 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 48 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 48 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 48 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 48 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 48 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 49 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 49 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 49 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 49 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 49 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 49 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 50 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 50 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 50 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 50 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 50 [5600/8000 (70%)]	Loss: 0.447608

Train Epoch: 71 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 71 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 71 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 71 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 72 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 72 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 72 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 72 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 72 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 72 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 73 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 73 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 73 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 73 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 73 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 73 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 74 [0/8000 (0%)]	Loss: 0.387669

Train Epoch: 95 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 95 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 95 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 95 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 95 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 96 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 96 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 96 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 96 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 96 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 96 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (79%)

Train Epoch: 97 [0/8000 (0%)]	Loss: 0.387669
Train Epoch: 97 [1400/8000 (17%)]	Loss: 0.323211
Train Epoch: 97 [2800/8000 (35%)]	Loss: 0.364323
Train Epoch: 97 [4200/8000 (52%)]	Loss: 0.486789
Train Epoch: 97 [5600/8000 (70%)]	Loss: 0.447608
Train Epoch: 97 [7000/8000 (87%)]	Loss: 0.521325

Test set: Average loss: 0.0344, Accuracy: 1584/2000 (7

### Step 3: Data transformation (make everything numerical)

In [8]:
def transform_to_numerical(data_df):
    dataset_df = data_df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
    dataset_df = pd.get_dummies(dataset_df)
    features = np.array(dataset_df.drop('Exited', axis=1))
    feature_names = dataset_df.drop('Exited', axis=1).columns.tolist()
    labels = np.array(dataset_df['Exited'])
    
    if len(features) > 1:
        features = (features - features.mean(axis=0, keepdims=True)) / features.std(axis=0, keepdims=True)
    
    return features, feature_names, labels

In [9]:
features, feature_names, labels = transform_to_numerical(data)
features, feature_names, labels

(array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
          1.09598752, -1.09598752],
        [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
          1.09598752, -1.09598752],
        [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
          1.09598752, -1.09598752],
        ...,
        [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
          1.09598752, -1.09598752],
        [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
         -0.91241915,  0.91241915],
        [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
          1.09598752, -1.09598752]]),
 ['CreditScore',
  'Age',
  'Tenure',
  'Balance',
  'NumOfProducts',
  'HasCrCard',
  'IsActiveMember',
  'EstimatedSalary',
  'Geography_France',
  'Geography_Germany',
  'Geography_Spain',
  'Gender_Female',
  'Gender_Male'],
 array([1, 0, 1, ..., 1, 1, 0]))

### Moving on to PyTorch!

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.nn.init as init
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler
from collections import OrderedDict
from torchvision import datasets, transforms

### Step 3.1 Create dataloaders

In [11]:
# Create a custom dataset
class ChurnModellingDataset(Dataset):
    def __init__(self, features, labels, transform=None,):
        assert features.shape[0] == labels.shape[0], "The lengths of features and labels do not match"

        self.feature_names = feature_names
        self.features = torch.tensor(features, dtype=torch.float)
        self.labels = torch.tensor(labels)
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, idx):
        return (self.features[idx], self.labels[idx])
    
    def get_feature_names(self):
        return self.feature_names

In [12]:
dataset = ChurnModellingDataset(features, labels)
len(dataset), dataset[0], len(dataset.get_feature_names())

(10000,
 (tensor([-0.3262,  0.2935, -1.0418, -1.2258, -0.9116,  0.6461,  0.9702,  0.0219,
           0.9972, -0.5787, -0.5738,  1.0960, -1.0960]),
  tensor(1)),
 13)

In [17]:
len(dataset)*(20)

200000

## My implementation

In [8]:
batch_size = 50
lr_rate = 0.01
epochs = 100
input_dim = 13
output_dim = 2

In [9]:
train_set, val_set = torch.utils.data.random_split(dataset, [8000, 2000])

In [10]:
len(train_set), len(val_set), type(train_set)

(8000, 2000, torch.utils.data.dataset.Subset)

In [11]:
train_loader = DataLoader(train_set, batch_size=batch_size)
test_loader = DataLoader(val_set, batch_size=batch_size)
len(train_loader), len(test_loader)

(160, 40)

In [12]:
 # Step 3. Create Model Class
class LogisticRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        outputs = self.linear(x)
        return outputs


In [13]:
def train(model, epoch, train_loader, loss_fn, optimizer):

    model.train()
    for batch_idx, (data, labels) in enumerate(train_loader):        
        # Forward pass: Compute predicted y by passing x to the model
        outputs = model(data)
        
        # Compute loss
        loss = loss_fn(outputs, labels)
        
        # Zero gradients, perform a backward pass, and update the weights.
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch_idx % 100 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))

def test(model, device, test_loader, loss_fn):
    
    model.eval()
    
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
#             data, target = data.to(device), target.to(device)
            outputs = model(data)
            test_loss += criterion(outputs, target)
            pred = outputs.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)

    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))

In [15]:
model = LogisticRegression(13, 2)

# Step 5. Instantiate Loss Class
criterion = torch.nn.CrossEntropyLoss() # computes softmax and then the cross entropy

# Step 6. Instantiate Optimizer Class
optimizer = torch.optim.Adam(model.parameters(), lr=lr_rate)

# Step 7. Train Model
for epoch in range(int(epochs)):
    train(model, epoch, train_loader, criterion, optimizer)
    test(model, None, test_loader, criterion)

Train Epoch: 0 [0/8000 (0%)]	Loss: 0.704951
Train Epoch: 0 [5000/8000 (62%)]	Loss: 0.472603

Test set: Average loss: 0.0087, Accuracy: 1620/2000 (81%)

Train Epoch: 1 [0/8000 (0%)]	Loss: 0.382423
Train Epoch: 1 [5000/8000 (62%)]	Loss: 0.481732

Test set: Average loss: 0.0087, Accuracy: 1620/2000 (81%)

Train Epoch: 2 [0/8000 (0%)]	Loss: 0.381224
Train Epoch: 2 [5000/8000 (62%)]	Loss: 0.482112

Test set: Average loss: 0.0087, Accuracy: 1617/2000 (81%)

Train Epoch: 3 [0/8000 (0%)]	Loss: 0.381236
Train Epoch: 3 [5000/8000 (62%)]	Loss: 0.482254

Test set: Average loss: 0.0087, Accuracy: 1617/2000 (81%)

Train Epoch: 4 [0/8000 (0%)]	Loss: 0.381233
Train Epoch: 4 [5000/8000 (62%)]	Loss: 0.482345

Test set: Average loss: 0.0087, Accuracy: 1617/2000 (81%)

Train Epoch: 5 [0/8000 (0%)]	Loss: 0.381226
Train Epoch: 5 [5000/8000 (62%)]	Loss: 0.482408

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 6 [0/8000 (0%)]	Loss: 0.381218
Train Epoch: 6 [5000/8000 (62%)]	Loss: 0.482

Train Epoch: 54 [5000/8000 (62%)]	Loss: 0.482625

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 55 [0/8000 (0%)]	Loss: 0.381177
Train Epoch: 55 [5000/8000 (62%)]	Loss: 0.482625

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 56 [0/8000 (0%)]	Loss: 0.381177
Train Epoch: 56 [5000/8000 (62%)]	Loss: 0.482625

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 57 [0/8000 (0%)]	Loss: 0.381177
Train Epoch: 57 [5000/8000 (62%)]	Loss: 0.482625

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 58 [0/8000 (0%)]	Loss: 0.381177
Train Epoch: 58 [5000/8000 (62%)]	Loss: 0.482625

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 59 [0/8000 (0%)]	Loss: 0.381177
Train Epoch: 59 [5000/8000 (62%)]	Loss: 0.482626

Test set: Average loss: 0.0087, Accuracy: 1615/2000 (81%)

Train Epoch: 60 [0/8000 (0%)]	Loss: 0.381177
Train Epoch: 60 [5000/8000 (62%)]	Loss: 0.482626

Test set: Average loss: 0.

## Predicted a untrained example

In [33]:
columns = ["RowNumber","CustomerId","Surname","CreditScore","Geography","Gender","Age","Tenure","Balance","NumOfProducts","HasCrCard","IsActiveMember","EstimatedSalary","Exited", 'Geography_Germany', 'Geography_Spain', 'Gender_Female']
data = [[1, 12121, "Any", 600, "France", "Male", 40, 3, 60000, 2, 1, 1, 50000, 1, 0,0,0]]
df = pd.DataFrame(data, columns=columns)
df
# record = np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
# record_label = np.array([0.0])
# loader = transforms.Compose([transforms.Normalize((0.1307,), (0.3081,)), transforms.ToTensor()])
# record = (record - record.mean(axis=0, keepdims=True)) / record.std(axis=0, keepdims=True)

RowNumber  CustomerId Surname  CreditScore Geography Gender  Age  Tenure  \
0          1       12121     Any          600    France   Male   40       3   

   Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0    60000              2          1               1            50000       1   

   Geography_Germany  Geography_Spain  Gender_Female  
0                  0                0              0

In [32]:
feature_names

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Geography_France',
 'Geography_Germany',
 'Geography_Spain',
 'Gender_Female',
 'Gender_Male']

In [35]:
record, record_features, record_label = transform_to_numerical(df)
record, record_features, record_label, len(record_features)

(array([[  600,    40,     3, 60000,     2,     1,     1, 50000,     0,
             0,     0,     1,     1]]),
 ['CreditScore',
  'Age',
  'Tenure',
  'Balance',
  'NumOfProducts',
  'HasCrCard',
  'IsActiveMember',
  'EstimatedSalary',
  'Geography_Germany',
  'Geography_Spain',
  'Gender_Female',
  'Geography_France',
  'Gender_Male'],
 array([1]),
 13)

In [66]:
record.std(axis=0, keepdims=True)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
dataset = ChurnModellingDataset(record, record_label)
len(dataset), dataset[0], len(dataset.get_feature_names())
sample_loader = DataLoader(dataset)

In [39]:
for images, labels in sample_loader:
    outputs = model(images)
    pred = outputs.argmax(dim=1, keepdim=True) 
    print(pred)

tensor([[1]])


In [38]:
outputs

tensor([[-20586.8164,  -3902.1030]], grad_fn=<AddmmBackward>)

## References
https://www.kaggle.com/dragonoken/churn-modelling-with-pytorch

In [29]:
############## DEPRECATED ##############
model = LogisticRegression(input_dim, output_dim)

# Step 5. Instantiate Loss Class
criterion = torch.nn.CrossEntropyLoss() # computes softmax and then the cross entropy

# Step 6. Instantiate Optimizer Class
optimizer = torch.optim.Adam(model.parameters(), lr=lr_rate)

# Step 7. Train Model
iter = 0
for epoch in range(int(epochs)):
    model.train()
    for i, (images, labels) in enumerate(train_loader):
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        iter+=1
        if iter%100==0:
            # calculate Accuracy
            correct = 0
            total = 0
            for images, labels in test_loader:
#                 images = Variable(images.view(-1, 28*28))
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                total+= labels.size(0)
                # for gpu, bring the predicted and labels back to cpu fro python operations to work
                correct+= (predicted == labels).sum()
            accuracy = 100 * correct/total
            print(f"Iteration: {i}. Loss: {loss.item()}. Accuracy: {accuracy}. epoch:{epoch}")

Iteration: 99. Loss: 0.45080384612083435. Accuracy: 80. epoch:0
Iteration: 199. Loss: 0.636818528175354. Accuracy: 81. epoch:0
Iteration: 299. Loss: 0.3298513889312744. Accuracy: 80. epoch:0
Iteration: 399. Loss: 0.15808606147766113. Accuracy: 80. epoch:0
Iteration: 499. Loss: 0.6422808170318604. Accuracy: 80. epoch:0
Iteration: 599. Loss: 0.38669145107269287. Accuracy: 80. epoch:0
Iteration: 699. Loss: 0.4859692454338074. Accuracy: 80. epoch:0
Iteration: 799. Loss: 0.8278332948684692. Accuracy: 80. epoch:0
Iteration: 99. Loss: 0.422950804233551. Accuracy: 81. epoch:1
Iteration: 199. Loss: 0.6574752926826477. Accuracy: 81. epoch:1
Iteration: 299. Loss: 0.32711881399154663. Accuracy: 80. epoch:1
Iteration: 399. Loss: 0.1563369184732437. Accuracy: 80. epoch:1
Iteration: 499. Loss: 0.642701268196106. Accuracy: 80. epoch:1
Iteration: 599. Loss: 0.3862289786338806. Accuracy: 80. epoch:1
Iteration: 699. Loss: 0.48686036467552185. Accuracy: 80. epoch:1
Iteration: 799. Loss: 0.8279159665107727

Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:16
Iteration: 299. Loss: 0.3272733986377716. Accuracy: 80. epoch:16
Iteration: 399. Loss: 0.15608082711696625. Accuracy: 80. epoch:16
Iteration: 499. Loss: 0.6427956819534302. Accuracy: 80. epoch:16
Iteration: 599. Loss: 0.3860437572002411. Accuracy: 80. epoch:16
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:16
Iteration: 799. Loss: 0.8279247283935547. Accuracy: 80. epoch:16
Iteration: 99. Loss: 0.422821581363678. Accuracy: 81. epoch:17
Iteration: 199. Loss: 0.657943606376648. Accuracy: 81. epoch:17
Iteration: 299. Loss: 0.32727333903312683. Accuracy: 80. epoch:17
Iteration: 399. Loss: 0.15608084201812744. Accuracy: 80. epoch:17
Iteration: 499. Loss: 0.6427956819534302. Accuracy: 80. epoch:17
Iteration: 599. Loss: 0.3860437572002411. Accuracy: 80. epoch:17
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:17
Iteration: 799. Loss: 0.8279246091842651. Accuracy: 80. epoch:17
Iteration: 99. Loss: 0.42

Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:32
Iteration: 299. Loss: 0.327273428440094. Accuracy: 80. epoch:32
Iteration: 399. Loss: 0.15608081221580505. Accuracy: 80. epoch:32
Iteration: 499. Loss: 0.6427956223487854. Accuracy: 80. epoch:32
Iteration: 599. Loss: 0.3860437870025635. Accuracy: 80. epoch:32
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:32
Iteration: 799. Loss: 0.8279246091842651. Accuracy: 80. epoch:32
Iteration: 99. Loss: 0.42282161116600037. Accuracy: 81. epoch:33
Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:33
Iteration: 299. Loss: 0.3272733986377716. Accuracy: 80. epoch:33
Iteration: 399. Loss: 0.15608081221580505. Accuracy: 80. epoch:33
Iteration: 499. Loss: 0.6427956819534302. Accuracy: 80. epoch:33
Iteration: 599. Loss: 0.3860437572002411. Accuracy: 80. epoch:33
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:33
Iteration: 799. Loss: 0.8279247283935547. Accuracy: 80. epoch:33
Iteration: 99. Loss: 0.4

Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:48
Iteration: 299. Loss: 0.32727333903312683. Accuracy: 80. epoch:48
Iteration: 399. Loss: 0.15608084201812744. Accuracy: 80. epoch:48
Iteration: 499. Loss: 0.6427956223487854. Accuracy: 80. epoch:48
Iteration: 599. Loss: 0.3860437273979187. Accuracy: 80. epoch:48
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:48
Iteration: 799. Loss: 0.8279246091842651. Accuracy: 80. epoch:48
Iteration: 99. Loss: 0.422821581363678. Accuracy: 81. epoch:49
Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:49
Iteration: 299. Loss: 0.3272733986377716. Accuracy: 80. epoch:49
Iteration: 399. Loss: 0.15608084201812744. Accuracy: 80. epoch:49
Iteration: 499. Loss: 0.6427956223487854. Accuracy: 80. epoch:49
Iteration: 599. Loss: 0.3860437870025635. Accuracy: 80. epoch:49
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:49
Iteration: 799. Loss: 0.8279247283935547. Accuracy: 80. epoch:49
Iteration: 99. Loss: 0.4

Iteration: 99. Loss: 0.422821581363678. Accuracy: 81. epoch:64
Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:64
Iteration: 299. Loss: 0.3272733986377716. Accuracy: 80. epoch:64
Iteration: 399. Loss: 0.15608081221580505. Accuracy: 80. epoch:64
Iteration: 499. Loss: 0.6427956819534302. Accuracy: 80. epoch:64
Iteration: 599. Loss: 0.3860437870025635. Accuracy: 80. epoch:64
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:64
Iteration: 799. Loss: 0.8279247283935547. Accuracy: 80. epoch:64
Iteration: 99. Loss: 0.422821581363678. Accuracy: 81. epoch:65
Iteration: 199. Loss: 0.6579435467720032. Accuracy: 81. epoch:65
Iteration: 299. Loss: 0.3272733986377716. Accuracy: 80. epoch:65
Iteration: 399. Loss: 0.15608084201812744. Accuracy: 80. epoch:65
Iteration: 499. Loss: 0.6427956223487854. Accuracy: 80. epoch:65
Iteration: 599. Loss: 0.3860437273979187. Accuracy: 80. epoch:65
Iteration: 699. Loss: 0.4872273802757263. Accuracy: 80. epoch:65
Iteration: 799. Loss: 0.827

KeyboardInterrupt: 